name: Rust debug build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '23 7 14 2,5,8,11 *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v6
      with:
        name: ssh_latency (linux)
        path: target/debug/ssh_latency
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v6
      with:
        name: ssh_latency (windows)
        path: target/debug/ssh_latency.exe
